language: go
sudo: false

go:
  - "1.11.x"

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get golang.org/x/lint/golint

script:
  - gofmt -l .
  - golint ./...
  - go tool vet -shadow .
  - go test -v -race -covermode=count -coverprofile=coverage.out ./...
  - goveralls -service=travis-ci
